import { test, expect } from '@playwright/test';

test('EN', async ({ page }) => {
  await page.goto('https://automoto.com.lv/en/advertising');
  await page.getByRole('link', { name: 'Request pricing' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Request pricing' }).first().click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Test@posta');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Get a consultation' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'View plans' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Call me back' }).click();
});

test('LV', async ({ page }) => {
  await page.goto('https://automoto.com.lv/lv/reklama');
  await page.getByRole('link', { name: 'Pieprasīt cenu' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).fill('Test');
  await page.getByRole('textbox', { name: 'Tālrunis' }).click();
  await page.getByRole('textbox', { name: 'Tālrunis' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'Es piekrītu AUTOMOTO.COM.LV' }).check();
  await page.getByRole('button', { name: 'Nosūtīt' }).click();
  await page.getByRole('link', { name: 'Atpakaļ' }).click();
  await page.getByRole('link', { name: 'Pieprasīt cenu' }).first().click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).fill('Test');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Test@posta');
  await page.getByRole('checkbox', { name: 'Es piekrītu AUTOMOTO.COM.LV' }).check();
  await page.getByRole('button', { name: 'Nosūtīt' }).click();
  await page.getByRole('link', { name: 'Atpakaļ' }).click();
  await page.getByRole('link', { name: 'Pieprasīt konsultāciju' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).fill('Test');
  await page.getByRole('textbox', { name: 'Tālrunis' }).click();
  await page.getByRole('textbox', { name: 'Tālrunis' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'Es piekrītu AUTOMOTO.COM.LV' }).check();
  await page.getByRole('button', { name: 'Nosūtīt' }).click();
  await page.getByRole('link', { name: 'Atpakaļ' }).click();
  await page.getByRole('link', { name: 'Skatīt plānus' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).click();
  await page.getByRole('textbox', { name: 'Jūsu vārds' }).fill('Test');
  await page.getByRole('textbox', { name: 'Tālrunis' }).click();
  await page.getByRole('textbox', { name: 'Tālrunis' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'Es piekrītu vietnes lietoš' }).check();
  await page.getByRole('button', { name: 'Piezvaniet man' }).click();
});

test('test', async ({ page }) => {
  await page.goto('https://automoto.com.lv/ru/reklama');
  await page.getByRole('link', { name: 'Узнать стоимость' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).fill('TestCheck');
  await page.getByRole('textbox', { name: 'Телефон' }).click();
  await page.getByRole('textbox', { name: 'Телефон' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'Я соглашаюсь с правилами использования сайта, а также с обработкой моих данных' }).check();
  await page.getByRole('button', { name: 'Отправить' }).click();
  await page.getByRole('link', { name: 'Назад' }).click();
  await page.getByRole('link', { name: 'Узнать стоимость' }).first().click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).fill('TestCheck');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Test@posta');
  await page.getByRole('checkbox', { name: 'Я соглашаюсь с правилами использования сайта, а также с обработкой моих данных' }).check();
  await page.getByRole('button', { name: 'Отправить' }).click();
  await page.getByRole('link', { name: 'Назад' }).click();
  await page.getByRole('link', { name: 'Запросить консультацию' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).fill('TestCheck');
  await page.getByRole('textbox', { name: 'Телефон' }).click();
  await page.getByRole('textbox', { name: 'Телефон' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'Я соглашаюсь с правилами использования сайта, а также с обработкой моих данных' }).check();
  await page.getByRole('button', { name: 'Отправить' }).click();
  await page.getByRole('link', { name: 'Назад' }).click();
  await page.getByRole('link', { name: 'Посмотреть пакеты' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).click();
  await page.getByRole('textbox', { name: 'Ваше имя' }).fill('TestCheck');
  await page.getByRole('textbox', { name: 'Телефон' }).click();
  await page.getByRole('textbox', { name: 'Телефон' }).fill('+37100000000');
  await page.locator('form div').filter({ hasText: 'Я соглашаюсь с правилами использования сайта, а также с обработкой моих данных' }).click();
  await page.getByRole('button', { name: 'Перезвоните мне' }).click();
});