import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automoto.com.lv/en/advertising');
  await page.getByRole('link', { name: 'Request pricing' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Request pricing' }).first().click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('Test@posta');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'Get a consultation' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('link', { name: 'Back' }).click();
  await page.getByRole('link', { name: 'View plans' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).click();
  await page.getByRole('textbox', { name: 'Your name' }).fill('Test');
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('+37100000000');
  await page.getByRole('checkbox', { name: 'I agree to the terms of use' }).check();
  await page.getByRole('button', { name: 'Call me back' }).click();
});