import { test, expect } from '@playwright/test';

test('EN', async ({ page }) => {
  await page.goto('https://automoto.com.lv/en/cars');
  await page.getByRole('dialog').getByText('Used', { exact: true }).click();
  await page.getByRole('dialog').getByText('New', { exact: true }).click();
  await page.getByText('All', { exact: true }).click();
  await page.getByLabel('Vehicle type').selectOption('1');
  await page.getByLabel('Fuel type').selectOption('1');
  await page.getByRole('radio', { name: 'Sedan Sedan' }).check();
  await page.getByRole('radio', { name: 'Hatchback Hatchback' }).check();
  await page.getByRole('radio', { name: 'Crossover Crossover' }).check();
  await page.getByRole('radio', { name: 'Minivan Minivan' }).check();
  await page.getByRole('radio', { name: 'Compact Compact' }).check();
  await page.getByRole('radio', { name: 'Liftback Liftback' }).check();
  await page.getByRole('radio', { name: 'Station Wagon Station Wagon' }).check();
  await page.getByLabel('Make').selectOption('53');
  await page.getByLabel('Model').selectOption('1753');
  await page.getByLabel('Year of manufacture').selectOption('1990');
  await page.locator('#yearTo').selectOption('2025');
  await page.getByLabel('Price').selectOption('500');
  await page.locator('#priceTo').selectOption('100000');
  await page.locator('.flex.items-center.justify-center.h-\\[30px\\].w-\\[30px\\].bg-black > .size-5').click();
  await page.locator('#country').selectOption('25');
  await page.getByLabel('Region').selectOption('7');
  await page.getByLabel('City').selectOption('7');
  await page.locator('#gearbox').selectOption('1');
  await page.getByLabel('Drivetrain').selectOption('1');
  await page.getByLabel('Drivetrain').selectOption('2');
  await page.getByLabel('Drivetrain').selectOption('3');
  await page.getByRole('button', { name: /Show \d+ listings/ }).click();
  await expect(page.locator('main h1, h1').first()).toBeVisible();
  await expect(page).toHaveTitle(/Cars for sale in Latvia | Buy used and new Vehicles on AUTOMOTO.COM.LV/i);
  const metaDescription = page.locator('meta[name="description"]');
  await expect(metaDescription).toHaveAttribute('content', /Looking for Cars among  ads for sale in Latvia ✅ Buy used and new Vehicles - best prices, photos, descriptions, wide selection, verified cars - AUTOMOTO.COM.LV/i);
  await page.getByText('Passenger cars').nth(4).click();
  await page.getByText('Petrol').nth(1).click();
  await page.getByText('Station Wagon').first().click();
  await page.getByText('Audi', { exact: true }).first().click();
  await page.getByText('A4').first().click();
  await page.getByText('Since 1990').click();
  await page.getByText('Until 2025').click();
  await page.getByText('Since 500 €').click();
  await page.getByText('Until 100000 €').click();
  await page.getByRole('dialog').getByText('Black').click();
  await page.getByText('Latvia', { exact: true }).first().click();
  await page.getByText('Ludza Municipality').first().click();
  await page.locator('.flex > div:nth-child(13)').first().click();
  await page.locator('.flex > div:nth-child(14)').first().click();
  await page.getByText('All wheel drive').first().click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});

test('LV', async ({ page }) => {
  await page.goto('https://automoto.com.lv/lv/auto');
  await page.getByLabel('Transportlīdzekļa tips').selectOption('1');
  await page.getByLabel('Degvielas tips').selectOption('7');
  await page.getByRole('radio', { name: 'Universāls Universāls' }).check();
  await page.getByRole('radio', { name: 'Liftbeks Liftbeks' }).check();
  await page.getByRole('radio', { name: 'Compact Compact' }).check();
  await page.getByRole('radio', { name: 'Minivens Minivens' }).check();
  await page.getByRole('radio', { name: 'Apvidus auto Apvidus auto' }).check();
  await page.getByRole('radio', { name: 'Hečbeks Hečbeks' }).check();
  await page.getByRole('radio', { name: 'Sedāns Sedāns' }).check();
  await page.getByLabel('Marka').selectOption('98');
  await page.getByLabel('Modelis').selectOption('820');
  await page.getByLabel('Izlaiduma gads').selectOption('1990');
  await page.locator('#yearTo').selectOption('2025');
  await page.getByLabel('Cena').selectOption('500');
  await page.locator('#priceTo').selectOption('100000');
  await page.locator('.flex.items-center.justify-center.h-\\[30px\\].w-\\[30px\\].bg-black').click();
  await page.locator('#country').selectOption('25');
  await page.getByLabel('Šalis').selectOption('7');
  await page.getByLabel('Pilsēta').selectOption('7');
  await page.locator('#gearbox').selectOption('1');
  await page.getByLabel('Piedziņas tips').selectOption('1');
  await page.getByRole('button', { name: /Parādīt \d+ sludinājumus/ }).click();
  await expect(page.locator('main h1, h1').first()).toBeVisible();
  await expect(page).toHaveTitle(/Automašīnas pārdošana Latvija | Nopirkt lietotas un jaunas Auto AUTOMOTO.COM.LV/i);
  const metaDescription = page.locator('meta[name="description"]');
  await expect(metaDescription).toHaveAttribute('content', /Meklējiet Automašīnas starp  sludinājumiem par pārdošanu Latvija ✅ Nopirkt lietotas un jaunas Auto - izdevīgas cenas, foto, apraksti, plaša izvēle, pārbaudītas automašīnas - AUTOMOTO.COM.LV/i);
  await page.getByText('Vieglie automobiļi').nth(4).click();
  await page.getByText('Dīzelis', { exact: true }).first().click();
  await page.getByText('Sedāns').first().click();
  await page.getByText('BMW', { exact: true }).first().click();
  await page.getByText('320', { exact: true }).first().click();
  await page.getByText('No 1990. gada').click();
  await page.getByText('Līdz 2025. gada').click();
  await page.getByText('No 500 €').click();
  await page.getByText('Līdz 100000 €').click();
  await page.getByRole('dialog').getByText('Melns').click();
  await page.getByText('Latvija', { exact: true }).first().click();
  await page.getByText('Ludzas novads').first().click();
  await page.locator('.flex > div:nth-child(13)').first().click();
  await page.locator('.flex > div:nth-child(14)').first().click();
  await page.getByText('Aizmugurējais piedziņa').first().click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});

test('RU', async ({ page }) => {
  await page.goto('https://automoto.com.lv/ru/avto');
  await page.getByLabel('Тип транспорта').selectOption('1');
  await page.getByLabel('Тип топлива').selectOption('8');
  await page.getByRole('radio', { name: 'Седан' }).check();
  await page.getByLabel('Марка').selectOption('732');
  await page.getByLabel('Модель').selectOption('21637');
  await page.getByLabel('Год выпуска').selectOption('1990');
  await page.locator('#yearTo').selectOption('2025');
  await page.getByLabel('Цена').selectOption('500');
  await page.locator('#priceTo').selectOption('100000');
  await page.locator('.flex.items-center.justify-center.h-\\[30px\\].w-\\[30px\\].bg-black').click();
  await page.locator('#country').selectOption('25');
  await page.getByLabel('Страна').selectOption('71');
  await page.getByLabel('Город').selectOption('20');
  await page.locator('#gearbox').selectOption('1');
  await page.getByLabel('Тип привода').selectOption('2');
  await page.getByRole('button', { name: /Показать \d+ объявлений/ }).click();
  await expect(page.locator('main h1, h1').first()).toBeVisible();
  await expect(page).toHaveTitle(/Продажа Авто Электро в Европе | Купить бу и новые Автомобили на AUTOMOTO.COM.LV/i);
  const metaDescription = page.locator('meta[name="description"]');
  await expect(metaDescription).toHaveAttribute('content', /Ищите Авто среди \d+ объявлений на продажу в Латвии ✅ Купить бу и новые Автомобили - .*(?:выгодные цены, )?.*, фото, описания, огромный выбор, проверенные авто - AUTOMOTO.COM.LV/i);
  await page.getByText('Легковые автомобили').first().click();
  await page.getByText('Электро', { exact: true }).nth(4).click();
  await page.getByText('Седан').nth(1).click();
  await page.getByText('Тесла').click();
  await page.getByText('Модель 3').click();
  await page.getByRole('dialog').getByText('Черный').click();
  await page.getByText('Латвия').first().click();
  await page.getByText('Рижский район').first().click();
  await page.getByText('Рига').nth(5).click();
  await page.getByText('Автомат', { exact: true }).nth(5).click();
  await page.getByText('Передний привод').first().click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});