import { test, expect } from '@playwright/test';

test('EN', async ({ page }) => {
  await page.goto('https://automoto.com.lv/en/cars');
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Date added ascending').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Date added descending').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Price: from low to high').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Price: from high to low').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Mileage: ascending').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Mileage: descending').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Year of manufacture: ascending').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Sorting' }).click();
  await page.getByText('Year of manufacture: descending').click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});

test('LV', async ({ page }) => {
  await page.goto('https://automoto.com.lv/lv/auto');
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc pievienošanas datuma (vispirms jaunākie)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc pievienošanas datuma (vispirms vecākie)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc cenas (augošā secībā)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc cenas (dilstošā secībā)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc nobraukuma (augošā secībā)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc nobraukuma (dilstošā secī').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc izgatavošanas gada (augo').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Kārtošana' }).click();
  await page.getByText('Pēc izgatavošanas gada (dilstošā secībā)').click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});

test('RU', async ({ page }) => {
  await page.goto('https://automoto.com.lv/ru/avto');
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По дате добавления (сначала старые)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По дате добавления (сначала новые)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По цене (по возрастанию)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По цене (по убыванию)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По пробегу (по возрастанию)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По пробегу (по убыванию)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По году выпуска (по возрастанию)').click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Сортировка' }).click();
  await page.getByText('По году выпуска (по убыванию)').click();
  await page.getByRole('link', { name: 'Logo CARS FROM LATVIA AT ONE' }).click();
});